### ISSUE TITLE
BadUSB/BT capslock activated (german layout)

### ISSUE THREAD

**Issue by philipneill** [akopachov/flipper-zero_authenticator#146]
First of all, thank you for this very nice tool!

The Bug:
If you use a german keyboard layout in windows, capslock is activated an then its outputing all those special characters, instead of the numbers.

To reproduce, just select a german keyboard layout and try.

**Comment by akopachov** [comment]
Thanks for reporting this!

I doubt I'd be able to find this bug myself given that I never use german keyboard layout 😄

**Comment by philipneill** [comment]
You dont need to use a physical layout, just change the windows keyboard to a german one and the issue will happen.

https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2#:~:text=the%20following%20methods.-,Change%20your%20keyboard%20layout,you%20have%20only%20one%20installed.)

**Comment by akopachov** [comment]
Thanks again for all the input. It allowed me to make this part of code easier and better than it was.

This should be fixed in [v2.0.3](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v2.0.3)

**Comment by philipneill** [comment]
Thank you so much!!
