### ISSUE TITLE
[FEATURE][UI] Exit text input screen using back button

### ISSUE THREAD

**Issue by zaygraveyard** [akopachov/flipper-zero_authenticator#148]
**Is your feature request related to a problem? Please describe.**
There's currently no way to exit the text input screen (like the token name and secret screens) without saving.

**Describe the solution you'd like**
It would be nice if pressing the back button when the input field is empty exits this screen without saving.

**Describe alternatives you've considered**
Another option is to allow saving when input field is empty.

**Additional context**
In builtin applications, pressing the back button immediately exits the text input screen.
I don't the use of the back button as a backspace but there should be a way to exit without saving.

**Comment by akopachov** [comment]
Implemented in [v2.1.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v2.1.0)
