### ISSUE TITLE
[BUG] Steam Guard seems to be broken

### ISSUE THREAD

**Issue by FLozyXD** [akopachov/flipper-zero_authenticator#149]
**Describe the bug**
I've just recovered secrets using the latest guide and Flipper shows the wrong code. However, by using this secret in Authenticator Pro I can get right codes.

**To Reproduce**
Just follow the latest guide to get secrets and add them via Flipper CLI

**Expected behavior**
It is expected to get correct Steam Guard codes from Flipper.

**Device information (please complete the following information):**
 - Firmware: Unleashed Firmware
 - Firmware version: dev-585e

**Additional context**
By the way, any other auth codes work fine

**Comment by akopachov** [comment]
Hey, just to make sure - did the secret token you extracted from steam looked like Base64-encoded? (alpha-numeric chars in different case and possible `/` and/or `=` symbols?

**Comment by FLozyXD** [comment]
Only letters and numbers, no other symbols. Took it from this string: "uri":"otpauth:\/\/totp\/Steam:[account_name]?secret=[SECRET]&issuer=Steam"

**Comment by akopachov** [comment]
Were those alphanumeric symbols all in the same case?

**Comment by FLozyXD** [comment]
Yep, all the letters were uppercase

**Comment by akopachov** [comment]
Then it looks like it is Base32-encoded, which is a bit weird for Steam secrets. Anyway, try update CLI command by changing `-e base64` to `-e base32`.

**Comment by FLozyXD** [comment]
Well... -e base32 works fine, bruh. Maybe add this to FAQ?

**Comment by akopachov** [comment]
Yeah, will definitely update wiki according to this finding (I never heard before about non-base64 encoded steam secrets). Thanks for reporting it!

**Comment by akopachov** [comment]
Updated [appropriate wiki section](https://github.com/akopachov/flipper-zero_authenticator/wiki/Does-it-support-Steam-style-tokens%3F) to better explain `-e base64` usage.
