### ISSUE TITLE
[BUG] API mismatch and signature failure.

### ISSUE THREAD

**Issue by Anatejl** [akopachov/flipper-zero_authenticator#153]
**Describe the bug**

After update for XFW48, it rolled out latest version, it returned errors, and didn't work. 
Then I reinstalled the app from repo manually, errors persist.

**To Reproduce**

1. Go to apps menu
2. Select authenticator
3. See error

**Expected behavior**

Regular behavior for the app 

**Screenshots**

![image](https://github.com/akopachov/flipper-zero_authenticator/assets/61248428/d25b88cc-7eb4-456c-b1b4-680bcfe40f37)

![image](https://github.com/akopachov/flipper-zero_authenticator/assets/61248428/1289cd8b-acdc-4fc9-93e7-51d60b22a182)

**Device information (please complete the following information):**
 - Firmware: XFW48
 - App - 2.1.1

**Additional context**

**Comment by ClaraCrazy** [comment]
api mismatch is just bc you installed it yourself, instead of using the fap provided. 

as for the digital verificatuon thingy, idk. thats an app specific thing. Have fun @akopachov

**Comment by ClaraCrazy** [comment]
Seems to me that [this](https://github.com/akopachov/flipper-zero_authenticator/blob/3538f31fe9cb051de9df0d3b0e9d2e7252da7810/totp/services/crypto/crypto.c#L120) function returns false for some reason. After trying to open my, luckily empty, authenticator app, I could confirm this issue. I havent had tea yet so im not quite sure how it works, but it seems fairly easy to fix. Although it might be slightly harder to securely fix it, as this is a security function

**Comment by akopachov** [comment]
Discussed that with @ClaraCrazy in DM. Looks like you changed flipper name which resulted to changing your flipper's UID and MAC. And the thing is that Authenticator app relies on UID when user is not setup PIN. We will try to find something better to rely on if possible. If not, then I guess there will not be any good choice other than 
1. Leave things as-is
2. Remove PIN-less authentication and force user to use PIN

Stay tuned...

**Comment by akopachov** [comment]
Should be fixed in [v2.2.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v2.2.0)
