### ISSUE TITLE
[FEATURE] Allow user to pick encryption key slot

### ISSUE THREAD

**Issue by akopachov** [akopachov/flipper-zero_authenticator#167]
Given [this](https://github.com/flipperdevices/flipperzero-firmware/issues/2885#issuecomment-1646664666) explanation I consider any key stored in slot number less than 5 as compromised. It is necessary to:

1. Implement migration to automatically migrate existing conf file to another default key slot
2. Let user change key slots via CLI

**Comment by akopachov** [comment]
`totp pin` command got updated to accept additional `-c <slot>` argument, allowing user to pick which key slot to use

**Comment by skotopes** [comment]
Explanation by @Skorp was incorrect, please see details in my comment https://github.com/flipperdevices/flipperzero-firmware/issues/2885#issuecomment-1652148724

**Comment by akopachov** [comment]
Thanks for explanation. I already made appropriate changes in v3.0.1 (#169)
