### ISSUE TITLE
[Question] Same answer as gnome authenticator?

### ISSUE THREAD

**Issue by FalcoGer** [akopachov/flipper-zero_authenticator#192]
Is it possible to import the data from another authenticator app, such as gnome authenticator? I still have the secrets/urls I entered into gnome authenticator, but no matter what setting I choose for flipper's authenticator, it's always different from what gnome authenticator spits out. I tried all the hashing algorithms and even added the timezone offset forward and backwards, but it just doesn't want to agree.

**Comment by akopachov** [comment]
It is possible to use Flipper Authenticator is you have plain token secret. If you have URI - that is also suitable, but **out of that URI you need to pick only secret piece**. 
Here is an example: 
![image](https://github.com/akopachov/flipper-zero_authenticator/assets/1217426/0eb50985-7252-4871-8859-c5d3e97b1038)

Then use [CLI](https://github.com/akopachov/flipper-zero_authenticator/wiki/Is-there-a-CLI%3F) to add this secret to the app. Just in case if generated token doesn't seems to be valid there could be [multiple reasons](https://github.com/akopachov/flipper-zero_authenticator/wiki/Flipper-Authenticator-generates-invalid-codes%2C-why-so%3F) why:
- Clock on device is not precise
- Timezone is not correct
- Token secret is not correct
- Token hashing algo is not correct

Usually it is either clock or timezone, but also worth to make sure token secret is correct too.

Related topics:
[How to migrate from another authenticator app?](https://github.com/akopachov/flipper-zero_authenticator/wiki/How-to-migrate-from-another-authenticator-app%3F)
[Flipper Authenticator generates invalid codes, why so?](https://github.com/akopachov/flipper-zero_authenticator/wiki/Flipper-Authenticator-generates-invalid-codes%2C-why-so%3F)
[Is there a CLI?](https://github.com/akopachov/flipper-zero_authenticator/wiki/Is-there-a-CLI%3F)

**Comment by akopachov** [comment]
Also, if you have original QR codes - you may use [companion app](https://github.com/akopachov/flipper-zero_authenticator-companion) to quickly add it to Authenticator app

**Comment by FalcoGer** [comment]
Thank you. Having the CLI really helped debug the issue. It was a timezone problem, but also for some reason the desktop application is about 20 seconds out of sync with the clock, despite the clocks being exactly the same (synced with qFlipper just moments before).

**Comment by FalcoGer** [comment]
Is it possible to have it switch timezones automatically with daylight savings?

**Comment by akopachov** [comment]
It is not possible as flipper is not aware of all different timezones and their dst rules. Implement such a database for flipper would overkill it :)
However I'll try to solve this in companion app for desktop to let it sync datetime and timezone at every run

**Comment by FalcoGer** [comment]
Flipper is aware of the date. I was thinking perhaps simply of a setting that would check that date and time and a flag and toggle between summer and winter time, then store that updated flag to storage. But maybe that is something that should be done at a higher level (flipper OS)?

**Comment by FalcoGer** [comment]
I will close this and open a new issue since it's off topic.
