### ISSUE TITLE
[FEATURE] Setting for summer/winter time automatically

### ISSUE THREAD

**Issue by FalcoGer** [akopachov/flipper-zero_authenticator#194]
**Is your feature request related to a problem? Please describe.**
Some countries use day light saving time that changes their timezone relative to UTC time. This requires manually adjusting the timezone offset for the application, which can catch users off guard and is annoying, error prone and confusing.

**Describe the solution you'd like**
A setting that allows users to set two offsets for the two time zone settings and a corresponding algorithm to check when to switch the setting over. Flipper is not aware of the timezone it is in, but it knows the current date and time.

**Describe alternatives you've considered**
Switching between timezones manually can be error prone. So perhaps entering them once and then having a toggle to switch between the two is better? Automation would certainly be preferred.

**Additional context**
Different countries may have different algorithms for determining when to switch the clocks. For example germany switches the clocks on the last Sunday of March (from 2:00AM to 3:00AM) and October (from 2:00AM to 1:00AM). I have no idea if that's universal or of other countries have different algorithms for determining when to switch.

**Comment by akopachov** [comment]
Unfortunately it is not possible to implement this in a reliable manner at application level given firmware restrictions. Might be possible only in case if flipper firmware itself would store and sync timezone information.

I'll add few more improvements to companion app [here](https://github.com/akopachov/flipper-zero_authenticator-companion/issues/3) to make user experience smoother.
