### ISSUE TITLE
How to change timezone from app?

### ISSUE THREAD

**Issue by vinogradovnet** [akopachov/flipper-zero_authenticator#2]
Can't generate correct OTP for my secret (16 letters)

Time checked - correct

All three SHA1, SHA256, SHA512 tried

All times OTP not match with other generators

How do I fix it?

UPDATE:

I changed "Timezone:" in totp.conf and OTP generated correctly.

Is it possible to set this value from app?

UPDATE: Found answer from you on Reddit. Will be nice to add info about timezone to doc. 

Thank you!

**Comment by vinogradovnet** [comment]
I changed "Timezone:" in totp.conf and OTP generated correctly.

Is it possible to set this value from app?

**Comment by akopachov** [comment]
Hey, glad you found solution. I do agree that Flipper Authenticator needs some UI to configure timezone. Also it definitely makes sense to add info to README. Good thing is that I plan to do both :) First of all - will update README, then UI.

**Comment by akopachov** [comment]
* README updated to explain better each key in conf file
* Timezone configuration UI was added in [release v0.0.6](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v0.0.6)
