### ISSUE TITLE
[BUG] Google Authenticator Tokens not working

### ISSUE THREAD

**Issue by Ay1tsMe** [akopachov/flipper-zero_authenticator#202]
**Describe the bug**
I was able to import my google authenticator tokens into the flipper zero authenticator. However, when i tried testing them on various websites, it says its incorrect. Im currently using the authenticator app built into the xtreme firmware. Is this error happening because this software needs to be updated so it works correctly with the companion?

**To Reproduce**
Steps to reproduce the behaviour:
1. Import google authenticator tokens
2. test them out and they dont work

**Comment by akopachov** [comment]
The app which is bundled into Xtreme should work just fine with companion. There are [multiple reasons](https://github.com/akopachov/flipper-zero_authenticator/wiki/Flipper-Authenticator-generates-invalid-codes%2C-why-so%3F) why generated codes might be invalid. Usually it is inaccurate time on flipper device or/and invalid timezone set in app settings. You may fix both of this using companion app, by going to "settings" and turning on "date time" and "timezone" synchronization.

**Comment by Ay1tsMe** [comment]
Adjusting the timezone offset fixed the issue. Thank you!
