### ISSUE TITLE
Building on Linux for Official FW

### ISSUE THREAD

**Issue by yasbean** [akopachov/flipper-zero_authenticator#211]
**Describe the bug**
I am trying to compile the latest version on linux using fbt (I do not have powershell) but the totp/features_config.h has been moved. When I build, I receive an ApiTooNew error.  Where can I set the build firmware version?

**Device information (please complete the following information):**
 - Firmware: Official stable
 - Firmware version 0.93.0

**Comment by akopachov** [comment]
Starting from v5 I updated all the necessary code to use [uFBT](https://github.com/flipperdevices/flipperzero-ufbt). 

Once you install it, all you need to do to build for latest official stable FW is:

```bash
cd totp
ufbt update --channel=release
ufbt
```

I also setup ["Nightly build" action](https://github.com/akopachov/flipper-zero_authenticator/actions/workflows/nightly-build.yml) which once per day builds latest application version using latest firmwares, so you may download and use its artifacts too

Just in case if you need very specific version of official stable firmware, then it is also possible using uFBT, just take a look at their ["Managing the SDK"](https://github.com/flipperdevices/flipperzero-ufbt#managing-the-sdk) section

**Comment by yasbean** [comment]
That has resolved it.  Thank you!

**Comment by yasbean** [comment]
That has resolved it. Thank you!
