### ISSUE TITLE
what is the counter?

### ISSUE THREAD

**Issue by grugnoymeme** [akopachov/flipper-zero_authenticator#212]
hi what is the totp counter?? where i can find it? thank u!

**Comment by akopachov** [comment]
Counter is needed for HOTP tokens only. Usually it is something what HOTP providers gives user together with secret. If it is not given by HOTP provider then highly-likely it is zero.

**Comment by akopachov** [comment]
Emphasizing - counter is HOTP-only thing, and is not applicable for TOTP token types

**Comment by grugnoymeme** [comment]
yes but flipper fap ask me the counter also for the totp...

**Comment by akopachov** [comment]
It is asking for counter only if HOTP token type is picked. Make sure you picked correct token type (HOTP VS TOTP).

**Comment by grugnoymeme** [comment]
yes.. it asking me for the totp.. idk...

**Comment by akopachov** [comment]
What is the firmware you are using?

**Comment by grugnoymeme** [comment]
unleashed

**Comment by akopachov** [comment]
Let's try to use fap and fal files from latest [nightly build for unleashed] (https://github.com/akopachov/flipper-zero_authenticator/actions/workflows/nightly-build.yml) as I'm not so sure what exact version is merged to Unleashed

**Comment by akopachov** [comment]
Nvm. Let me dig more. I think I know what could be wrong

**Comment by akopachov** [comment]
Should be fixed in [v5.6.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v5.6.0)

**Comment by grugnoymeme** [comment]
ok i'll try this evening
