### ISSUE TITLE
[FEATURE] Keys export

### ISSUE THREAD

**Issue by UndeRus** [akopachov/flipper-zero_authenticator#219]
**Is your feature request related to a problem? Please describe.**
I want to export keys from flipper to any external application

**Describe the solution you'd like**
Make ability to export keys from flipper zero

**Describe alternatives you've considered**
It may be implemented with keyboard output

**Comment by akopachov** [comment]
Should be implemented in [v5.10.0](https://github.com/akopachov/flipper-zero_authenticator/releases/latest).

New CLI command `totp export` has been added. As a result of running this command an [URI list](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) will be generated and printed to the console. This list should contain all the necessary information and be compatible with any authenticator allowing to import URI list files.

**Comment by UndeRus** [comment]
Thank you very much for this feature! I already thought that I had lost my keys)
