### ISSUE TITLE
Flipper Zero with latest official release will result in "API version mismatch" when installing from latest release (5.10.0)

### ISSUE THREAD

**Issue by besi** [akopachov/flipper-zero_authenticator#221]
I just got a new flipper zero and it is up to date with the latest official firmware

```
Version 0.98.2
Build date: 1.02.2024
Hardware: 12.F7****
Radio FW: 1.17.3 LITE
```

There are currently four open issues with regards to API version mismatch:
These people seem to be facing different issues than I am so this is why I'm opening a new issue here.

- #92 building from source
- #76 A year ago using a specific commit
- #16 using UNLSHD-012 (closed)
- #1 quite old

I did the following:

1. Plugin the flipper
2. Download `v5.10.0` [totp_official-stable_fw.zip](https://github.com/akopachov/flipper-zero_authenticator/releases/download/v5.10.0/totp_official-stable_fw.zip)
3. Extract all files onto the root SD card
4. Attempt to run `totp` which has a question mark for an icon
5. Error
     ![Screenshot-20240204-113619](https://github.com/akopachov/flipper-zero_authenticator/assets/160412/0f5f03ea-7f34-4da0-86cc-36fbc7565e69)
6. Restart the flipper using LEFT + BACK
7. Try the same thing with [totp_unleashed_fw.zip](https://github.com/akopachov/flipper-zero_authenticator/releases/download/v5.10.0/totp_unleashed_fw.zip) since I read in one  of those issues that unleased works against the same API as the official firmware.
8. Same result :-(

![Screenshot-20240204-114935](https://github.com/akopachov/flipper-zero_authenticator/assets/160412/0ef05840-3800-434c-bce4-56cce99d6c7a)

I am not yet ready to attempt to build the project from source and I just wanted to give your app a spin so I do wonder how to run it on my new flipper running the latest official firmware...

Anyhow thanks for investing a lot of time and effort in something that's useful for a lot of people.

**Comment by akopachov** [comment]
You may try the artifact from nightly build -
https://github.com/akopachov/flipper-zero_authenticator/actions/workflows/nightly-build.yml
This action runs once a day building master branch over latest firmwares,
so highly - likely it should work for you.
If not - let me know and I'll build it manually.

**Comment by besi** [comment]
@akopachov: I did try the latest version and I'm up and running now. Thanks!
