### ISSUE TITLE
[FEATURE]Menu button

### ISSUE THREAD

**Issue by YupengLai4** [akopachov/flipper-zero_authenticator#228]
Hi, I genuinely love this feature:) I've input all my verification codes into it. However, it has become quite cumbersome to use now, as I need to scroll left and right numerous times to find the specific code I need. I suggest implementing a menu to display the names of the codes, making it much easier to locate the desired one.

**Comment by akopachov** [comment]
Hey, thanks for the suggestion!

Doesn't that menu just change the navigation pattern from "scroll left and right numerous times to find the specific code" to "scroll up and bottom numerous times to find the specific code"?

**Comment by YupengLai4** [comment]
Ohh, I think you are right...
