### ISSUE TITLE
[BUG] Null pointer dereference on latest official firmware

### ISSUE THREAD

**Issue by RingoAl** [akopachov/flipper-zero_authenticator#233]
After running app and enter pin, Flipper crashes and show "NULL pointer dereference" error

**To Reproduce**
1. Install latest official firmware (0.102.3)
2. Build app (I've done it wia ufbt: cd totp, ufbt update, ufbt build)
3. Run app
4. Enter pin
5. See crash and error

**Expected behavior**
App works fine

**Screenshots**
![image](https://github.com/akopachov/flipper-zero_authenticator/assets/18333359/d4776b54-35c7-4dfd-8c98-23c53f4254e3)

**Device information (please complete the following information):**
 - Firmware: Official stable
 - Firmware version 0.102.3

**Comment by akopachov** [comment]
Have you installed and run Authenticator previously on your device?
Is there `/ext/apps_data/totp/totp.conf`?

**Comment by RingoAl** [comment]
>Have you installed and run Authenticator previously on your device?
Yes
>Does /ext/apps_data/totp/totp.conf file exist?
Yes

**Comment by akopachov** [comment]
Could you please share `Version` and `CryptoVersion` properties out of `/ext/apps_data/totp/totp.conf`?

**Comment by RingoAl** [comment]
Filetype: Flipper TOTP plugin config file
Version: 12
CryptoVersion: 3

**Comment by RingoAl** [comment]
Flipper freezes on black screen on latest dev (F309844E) after pin

**Comment by akopachov** [comment]
So far can't reproduce it on my flipper running official stable (0.102.3).

If you delete `/ext/apps_data/totp/totp.conf` (**take backup of it before**) does app start normally?

**Comment by RingoAl** [comment]
I've renamed totp.conf.
App starts normally, asks for pin setup and crashes with same error on "Add new token"

**Comment by akopachov** [comment]
Did exactly the same steps - still working just fine on my side.
Let's try to use Authenticator from the [latest nightly build](https://github.com/akopachov/flipper-zero_authenticator/actions/runs/9286344794/artifacts/1548289716).

**Comment by RingoAl** [comment]
This build works fine, thanks.

**Comment by akopachov** [comment]
No problem. Probably you were building outdated code or so. In any case - glad it works fine for you now
