### ISSUE TITLE
[FEATURE] Additional confirmation of the export

### ISSUE THREAD

**Issue by akopachov** [akopachov/flipper-zero_authenticator#240]
Would be better if the user would need to confirm he agrees to export by pressing the buttons on flipper device

**Comment by JIANAN16** [comment]
i only managed to download the companion app so far

**Comment by akopachov** [comment]
> what do u even download to use this google authenticator thing? u did not specify at all

There is appropriate [wiki page](https://github.com/akopachov/flipper-zero_authenticator/wiki/How-to-get-it%3F), that is covering this question. Read it first.
