### ISSUE TITLE
[BUG] Didn't works on Unleashed 078

### ISSUE THREAD

**Issue by the-davinci-code** [akopachov/flipper-zero_authenticator#244]
used to use your application, but at that time I had the Xtreme firmware installed, and everything worked without any problems. But now, when I switched to Unleashed, I encountered the issue that this application cannot be used on this firmware. The application icon does not load:
![Screenshot-20241025-083149](https://github.com/user-attachments/assets/b56935b4-fc99-4a7c-b626-9e98199498b0)
 When logging in, there is even a notification that the application may work unstable:
![Screenshot-20241025-082129](https://github.com/user-attachments/assets/62561a20-f2b7-4c4f-b98b-e29ef8cffb26)
And most importantly, on the Unleashed firmware, it is impossible to add tokens using [Companion](https://github.com/akopachov/flipper-zero_authenticator-companion):
![Screenshot 2024-10-25 at 8 21 59 AM](https://github.com/user-attachments/assets/42123826-797f-4e68-aa8a-c275dc4878be)

**Comment by akopachov** [comment]
It looks like Authenticator app you have is out of date. It is sort of strange, given the fact that Unleashed has it prebuilt, so I assume you installed it manually somehow for some reason. Which is fine.

Try installing Authenticator from [Nightly builds here](https://github.com/akopachov/flipper-zero_authenticator/actions/workflows/nightly-build.yml), they are running every day and it allows to keep them up to date with the latest firmwares.

**Comment by the-davinci-code** [comment]
Thank you, I will try your solution today. But this is very strange: do you mean that there is a version of Unleashed firmware where Authenticator is already installed? It seems I have installed all versions of Unleashed (default, c, e, r) and did not see your application in any of them.

**Comment by akopachov** [comment]
that's correct. Authenticator is included even in Unleashed default. So it should be there in "Apps/Tools" category. If you have an issue with it, consider raising a question in Unleashed repo, probably the maintainer there would be able to explain what is wrong.
