### ISSUE TITLE
Command totp add without secret crashes Flipper with furi_check failed

### ISSUE THREAD

**Issue by kowalski7cc** [akopachov/flipper-zero_authenticator#51]
Adding a new secret from cli without entering a secret will crash flipper with `furi_check failed`.

Steps to reproduce:
1. Open totp app and unlock
2. Open shell and type `totp add secret`
3. Press enter without typing anything

**Comment by akopachov** [comment]
Thank you for reporting it!
Working on it now

**Comment by akopachov** [comment]
Fixed in [v1.5.3](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v1.5.3)
