### ISSUE TITLE
Flipper dead After test

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [akopachov/flipper-zero_authenticator#53]
I added a test token:

Name: q
Secret: q
Algo: SHA256

After Crash no token saved

Maybe add a error if invalid secret ist supplied?

**Comment by akopachov** [comment]
Thank you for reporting it

**Comment by akopachov** [comment]
Fixed in [v1.5.4](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v1.5.4)
