### ISSUE TITLE
Daylight Savings Breaks TOTP

### ISSUE THREAD

**Issue by iplusplus42** [akopachov/flipper-zero_authenticator#90]
Daylight Savings Time seems to have broken TOTP on my Flipper. None of my TOTP codes work unless I manually set my phone's time one hour back and have that sync to the Flipper.

**Comment by iplusplus42** [comment]
Never mind, I completely forgot that you could change the timezone in the TOTP app. However, this would be a great FAQ addition.

**Comment by akopachov** [comment]
Agree. Worth it to explain in FAQ

**Comment by akopachov** [comment]
Added [wiki page](https://github.com/akopachov/flipper-zero_authenticator/wiki/TOTP-codes-became-invalid-after-daylight-saving-time-switch,-why%3F)
